cors:
  originPatterns: http://localhost:8080,https://jujubaprojects.com.br,http://localhost:3000 # sem espacos
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/rest-app-spring-boot
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

# Configurações específicas do Flyway
flyway:
  locations: classpath:db/migration  # Especifica o diretório onde os scripts SQL do Flyway estão localizados
  baselineOnMigrate: true             # Cria uma linha de base se ela ainda não existir

server:
  error:
    whitelabel:
      enabled: false
    spring-doc:
      pathsToMatch: /api/**/v1/**
       # essa configuração está instruindo o Springdoc a 
      #considerar para documentação apenas os caminhos que seguem o padrão /api/**/v1/** na sua aplicação.

     # /api/user/v1/get ou /api/products/v1/details, esses serão incluídos na documentação gerada pelo Springdoc.
     #  Essa abordagem facilita a organização e a apresentação da documentação, especialmente em casos onde há múltiplas versões da API.
    swagger-ui: 
     use-root-path:true





